services:
    php:
        build:
            target: php_dev
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: >-
                client_host=host.docker.internal
                idekey=PHPSTORM
                start_with_request=yes
                discover_client_host=1
                log_level=0
            PHP_IDE_CONFIG: "serverName=docker-php83"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    # wiremock:
    #     image: "holomekc/wiremock-gui:latest"
    #     container_name: wiremock
    #     environment:
    #         WIREMOCK_OPTIONS: "--enable-stub-cors"
    #     volumes:
    #       - ./wiremock/mappings:/home/wiremock/mappings
    #       - ./wiremock/files:/home/wiremock/__files
    #     ports:
    #         - "8888:8080"
    apache:
        ports: !override
            - "8081:80"
    mysql:
        ports: !override
            - "3308:3306"
